// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Persimmon")>]
[<assembly: AssemblyProductAttribute("Persimmon")>]
[<assembly: AssemblyVersionAttribute("5.0.0")>]
[<assembly: AssemblyFileVersionAttribute("5.0.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Persimmon"
    let [<Literal>] AssemblyProduct = "Persimmon"
    let [<Literal>] AssemblyVersion = "5.0.0"
    let [<Literal>] AssemblyFileVersion = "5.0.0"
    let [<Literal>] AssemblyConfiguration = "Release"
