// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Persimmon")>]
[<assembly: AssemblyDescriptionAttribute("")>]
[<assembly: AssemblyProductAttribute("Persimmon")>]
[<assembly: AssemblyVersionAttribute("3.1.1")>]
[<assembly: AssemblyFileVersionAttribute("3.1.1")>]
[<assembly: AssemblyInformationalVersionAttribute("3.1.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Persimmon"
    let [<Literal>] AssemblyDescription = ""
    let [<Literal>] AssemblyProduct = "Persimmon"
    let [<Literal>] AssemblyVersion = "3.1.1"
    let [<Literal>] AssemblyFileVersion = "3.1.1"
    let [<Literal>] AssemblyInformationalVersion = "3.1.1"
