// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Persimmon.Console")>]
[<assembly: AssemblyProductAttribute("Persimmon")>]
[<assembly: AssemblyVersionAttribute("4.0.2")>]
[<assembly: AssemblyFileVersionAttribute("4.0.2")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Persimmon.Console"
    let [<Literal>] AssemblyProduct = "Persimmon"
    let [<Literal>] AssemblyVersion = "4.0.2"
    let [<Literal>] AssemblyFileVersion = "4.0.2"
    let [<Literal>] AssemblyConfiguration = "Release"
