// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Persimmon.Runner")>]
[<assembly: AssemblyDescriptionAttribute("")>]
[<assembly: AssemblyProductAttribute("Persimmon")>]
[<assembly: AssemblyVersionAttribute("3.1.0")>]
[<assembly: AssemblyFileVersionAttribute("3.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("3.1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Persimmon.Runner"
    let [<Literal>] AssemblyDescription = ""
    let [<Literal>] AssemblyProduct = "Persimmon"
    let [<Literal>] AssemblyVersion = "3.1.0"
    let [<Literal>] AssemblyFileVersion = "3.1.0"
    let [<Literal>] AssemblyInformationalVersion = "3.1.0"
