// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Persimmon.Runner")>]
[<assembly: AssemblyDescriptionAttribute("")>]
[<assembly: AssemblyProductAttribute("Persimmon")>]
[<assembly: AssemblyVersionAttribute("2.0.1")>]
[<assembly: AssemblyFileVersionAttribute("2.0.1")>]
[<assembly: AssemblyInformationalVersionAttribute("2.0.1-alpha6")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Persimmon.Runner"
    let [<Literal>] AssemblyDescription = ""
    let [<Literal>] AssemblyProduct = "Persimmon"
    let [<Literal>] AssemblyVersion = "2.0.1"
    let [<Literal>] AssemblyFileVersion = "2.0.1"
    let [<Literal>] AssemblyInformationalVersion = "2.0.1-alpha6"
